version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql_sghss
    restart: always
    environment:
      MYSQL_DATABASE: sghss_db
      MYSQL_USER: sghss_user
      MYSQL_PASSWORD: sghss_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  sghss-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sghss_api
    depends_on:
      - mysql
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sghss_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: sghss_user
      SPRING_DATASOURCE_PASSWORD: sghss_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8088:8088"

volumes:
  mysql_data: