server:
  port: 8088
  servlet:
    context-path: /api

spring:
  application:
    name: sghss

  # Configuração do Banco de Dados MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare_api?useSSL=false&serverTimezone=UTC
    username: root
    password: dcadmin2288
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuração do Hibernate/JPA
  jpa:
    hibernate:
      ddl-auto: none # Pode ser 'validate' ou 'none' em produção
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Configuração do Flyway para versionamento do banco
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Configuração do JWT (Autenticação)
jwt:
  private:
    key: classpath:key/private.pem
  public:
    key: classpath:key/public.pem

# Configuração de Logs
logging:
  level:
    root: INFO
    org.springframework: INFO
    br.eng.campoy.sghss: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html